### ISSUE TITLE
restartApp() does not work on Firefox 45

### ISSUE THREAD

**Issue by gardejo** [mooz/keysnail#197]
# Synopsis

It seems that the built-in command `restartApp()` does not work correctly on Firefox 45.

# Events

## Environment

* Windows 10 Pro 64bit (ja), Windows 10 Home 32bit (ja), Windows 8.1 32bit (ja), etc.
* Firefox 45.0.0-45.0.1 (ja_JP) 32bit/64bit with a brand-new profile
    * Note: The problem does not appear on Firefox 44.0.
* KeySnail 2.1.9

## Steps to reproduce

We can recreate the circumstances of the problem:

1. Prepare to run the built-in command `restartApp()` with any way.
    * ex. Bind it with any key sequence.
2. Run it.

## Expected events

1. Firefox will quit itself.
2. And Firefox will restart (with tabs and sessions) automatically.

## Actual events

1. Firefox will quit itself.
2. But Firefox will not restart automatically.
3. I can (re)start Firefox manually, but Firefox will not resume tabs and sessions.

This behavior is reproducible at all times.

# Causes

## Immediate cause

It seems that the Firefox will be crushed between [/content/modules/command.js Line 1513](https://github.com/mooz/keysnail/blob/6aea7da51cd9115195396c8bbcda4c226038958f/content/modules/command.js#L1513):

    os.notifyObservers(null, "quit-application-granted", null);

I copied `restartApp()` function into my initialization file (`.keysnail.js`) and commented-out the line on trial.
Then, that looks like the function is working correctly *on the face*.

## Fundamental cause

Unknown, sorry.

**Comment by timss** [comment]
@mooz We have a [restart](https://github.com/vimperator/vimperator-labs/blob/68ae0c183b5c09278c0d12c096f6033f0ea7f9e8/common/content/liberator.js#L992) function in Vimperator as well which is using `nsIObserverService.notifyObservers()` with the `quit-application-granted` flag. 

I just confirmed that it indeed broke between FF 44 and FF 45, and that removing it like you did is a possible fix, but do you know why it was changed or if it was intentional? Can't find any references in the documentation that explains why it suddenly changed.

Relevant issue: https://github.com/vimperator/vimperator-labs/issues/460

Thanks.
