### ISSUE TITLE
Firefox 57.0a1 (2017-08-06) breaks Keysnail

### ISSUE THREAD

**Issue by jbeich** [mooz/keysnail#222]
Keysnail bindings no longer work after [bug 1375125](https://bugzilla.mozilla.org/show_bug.cgi?id=1375125).

### Steps to reproduce
1. Install Firefox Nightly build 20170806100257 or later
2. Allow legacy/non-mpc extensions per [wiki](https://wiki.mozilla.org/Add-ons/Firefox57#Prefs)
3. Install Keysnail
4. Create ~/.keysnail.js with Emacs/w3m keybindings
5. C-t (Open new tab)
6. C-x k (Close tab)
7. C-x C-c (Close browser)

### Actual result
6 and 7 steps do nothing

### Expected result
6 and 7 do desired actions

### Workaround
Locally revert mozilla/gecko-dev@06311d2e3abf, switch to Beta 56 or ESR52

### Browser console
```
KeySnail.initModule :: [Exception... "Component returned failure code: 0x80570018 (NS_ERROR_XPC_BAD_IID) [nsIJSCID.createInstance]"  nsresult: "0x80570018 (NS_ERROR_XPC_BAD_IID)"  location: "JS frame :: chrome://keysnail/content/modules/util.js :: openFile :: line 171"  data: no]
[Exception... "Component returned failure code: 0x80570018 (NS_ERROR_XPC_BAD_IID) [nsIJSCID.createInstance]"  nsresult: "0x80570018 (NS_ERROR_XPC_BAD_IID)"  location: "JS frame :: chrome://keysnail/content/modules/util.js :: openFile :: line 171"  data: no]  (unknown)
```

**Comment by jbeich** [comment]
Also, [bug 1387009](https://bugzilla.mozilla.org/show_bug.cgi?id=1387009) a few days before broke `select_(next|previous)_tab` and `close_all_tabs_on_(left|right)`.

**Comment by Inops** [comment]
It might be an idea for someone to make the necessary changes to allow KeySnail to work out-of-the-box with Pale Moon. It complains about being "not compatible" with Pale Moon, but after installing an extension to prevent compatibility checks, it works as expected. Pale Moon isn't dropping XUL extension support, so perhaps this is a good way for KeySnail to live on, without necessitating a massive (and less powerful) rewrite.

**Comment by phil-s** [comment]
For Pale Moon I copied my `~/.mozilla/firefox/(profile)/extensions/keysnail@mooz.github.com` directory into to `~/.moonchild productions/pale moon/(profile)/extensions/` and edited its `install.rdf` file and, based on the GUID listed at https://forum.palemoon.org/viewtopic.php?p=55987#p55987 , changed the target application element to:

        
        <em:targetApplication>
            <Description>
                <em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
                <em:minVersion>25.*</em:minVersion>
                <em:maxVersion>99.*</em:maxVersion>
            </Description>
        </em:targetApplication>

After restarting Pale Moon I was able to enable KeySnail.

**Comment by smallst** [comment]
archlinux is upgrading ff to 57. need keysnail QAQ

**Comment by mooz** [comment]
All,

Sorry for the late response. Since Firefox 57 dropped several important features required by KeySnail (or Vimperator), there is no chance to migrate KeySnail to Firefox 57+ for now.

The most important feature, which has been unfortunately dropped in Firefox 57+, is API for overriding browser-level shortcut keys. See https://bugzilla.mozilla.org/show_bug.cgi?id=1215061 for details. Since current API only allows content-level shortcut keys, KeySnail doesn't work in most of the places including location bars, search field, and so forth.

If you want to keep using KeySnail, I recommend using Waterfox https://www.waterfoxproject.org/ instead of Firefox. Several KeySnail users have already reported that they are enjoying Waterfox.

Another option is to switch to other add-ons that still work in Firefox 57+. I tried several add-ons and personally recommend Vimium-ff https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/

Thanks for using KeySnail! Without your encouraging reactions, I couldn't enjoy such a long-time lasting development.

mooz
